name: Build Docker Release
on:
  release:
    types: [published]

jobs:
  build-and-push-docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        run: |
          export VERSION=`node -e "console.log(require('./package').version)"`
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        id: extract_version
      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/ctfd/tourist:latest
            ghcr.io/ctfd/tourist:${{ steps.extract_version.outputs.version }}
