name: Build Docker

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build-and-push-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: milymilo
          password: ${{ secrets.CR_PAT }}
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract version
        run: |
        export VERSION=`node -e "console.log(require('./package').version)"`
        echo "::set-output name=VERSION::$VERSION"
        id: extract_version
      - name: Build and push feature branch
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
          ghcr.io/milymilo/tourist:${{ steps.extract_branch.outputs.branch }}
      - name: Build and push latest
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
          ghcr.io/milymilo/tourist:latest
          ghcr.io/milymilo/tourist:${{ steps.extract_version.outputs.version }}